name: Deploy to Server

on:
  push:
    branches:  [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: scp -r * ubuntu@35.154.205.209:/home/aditya/timetrack2/

    - name: Run deployment script
      run: ssh ubuntu@35.154.205.209 'bash /home/aditya/timetrack2/pullstart.sh'
